import { NextPage } from "next";
import Head from 'next/head';
import { Container, Col, Row } from "react-bootstrap";
import { useSelector } from "react-redux";
import OrderList from "../../components/lists/orderList";
import { selectOrdersState } from "../../store/userSlice";

const Orders: NextPage = () => {

    const orders=useSelector(selectOrdersState);

    return (
        <>
            <Head>
                <title>Store-App orders</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <Container>
                <Row >
                    {orders.length > 0 ? <OrderList list={orders} ></OrderList> :<></>}
                </Row>
            </Container>
        </>
    )



}


export default Orders;
