import type { GetServerSideProps, } from 'next'
import axios from 'axios';
import type { NextPage } from 'next'
import Head from 'next/head';
import ProdList from '../components/lists/prodList';
import SellerList from '../components/lists/sellerList';
import MainCarousel from '../components/widgets/mainCarousel';
import MainCatList from '../components/widgets/mainCatList';
import { Container,Col,Row,Image} from 'react-bootstrap';
import { baseUrl } from '../utils/config';
import  {List} from '../types/list';
import { config } from 'process';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faCartShopping,faDollarSign,faCircle,faHeadset } from '@fortawesome/free-solid-svg-icons'

const Home: NextPage = ({products} : any) => {

  // const lists: List[] = [
  //   {
  //     title: 'Facebook With friends and age',
  //     items: [
  //       {
  //         title: 'FB Accounts | [PVA] 100+ followers (friends and followers). Verified by email, Email@mail.ru included. Female. Partially filled profiles. 2FA in the set. Registered from Bangladesh IP.',
  //         in_stock: 1,
  //         price: 4,
  //         category:{
  //           id:23,
  //           type:'main',
  //           title:'facebook',
  //           media:[{}]
  //         },
  //       },

  const lists: List[]=[
    {
      title:'المنتجات الاكثر مبيعا',
      items:[
        {
          id:1,
          title:'tttttt',
          in_stock:12,
          price:1212,
          
        },
        {
          id:2,
          title:'tttttt',
          in_stock:12,
          price:1212,
          
        },
        {
          id:3,
          title:'tttttt',
          in_stock:12,
          price:1212,
          
        },
        {
          id:4,
          title:'tttttt',
          in_stock:12,
          price:1212,
          
        },
      ]
    },
    {
      title:'منتجات صدرت حديثا',
      items:[
        {
          id:5,
          title:'tttttt',
          in_stock:12,
          price:1212,
          
        },
        {
          id:6,
          title:'tttttt',
          in_stock:12,
          price:1212,
          
        },
        {
          id:7,
          title:'tttttt',
          in_stock:12,
          price:1212,
          
        },
        {
          id:8,
          title:'tttttt',
          in_stock:12,
          price:1212,
          
        },
      ]
    },
  ]


  return (
    <>
      <Head>
        <title>Store-App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container fluid className='px-0' >
        <MainCarousel></MainCarousel>
      </Container>
      <Container className='my-4'>
        <Image src='https://cdn.salla.sa/form-builder/J1GR2dtpzPcSZrwTp2iuY5EahfzXcM0xM0e3twot.png' alt='trusted by marrouf' fluid></Image>
        {/* <Image src="https://cdn.salla.sa/form-builder/J1GR2dtpzPcSZrwTp2iuY5EahfzXcM0xM0e3twot.png" alt="trusted by marrouf"></Image> */}
      {/* <ProdList list={{title:'products from back-end',category:'facebook', items:products}}></ProdList> */}
      </Container>
      <Container>
        {lists.map((list,key) =>  <ProdList list={list} key={key}></ProdList> )}
      </Container>
      <Container className='text-center py-2 my-2 bg-white' fluid>
        <h2 className="section-title mb-4">مزايا المتجر</h2>
          <Container>
            <Row>
              <Col sm={6} md={4}>
                <span className="fa-layers fa-fw my-4">
                  <FontAwesomeIcon icon={faCircle} size="3x" /> 
                  <FontAwesomeIcon icon={faCartShopping} size="1x" className='px-3' color="white" /> 
                </span>
                <h3 className='feature_title'> طرق التسليم </h3>
                <p> التسليم فوري في أقل من دقيقه </p>
              </Col>
              <Col sm={6} md={4}>
                <span className="fa-layers fa-fw my-4">
                  <FontAwesomeIcon icon={faCircle} size="3x" /> 
                  <FontAwesomeIcon icon={faHeadset} size="1x" className='px-3' color="white" /> 
                </span>
                <h3 className='feature_title'> الدعم الفني </h3>
                <p> دعم فني متواصل 7\24 </p>
              </Col>
              <Col sm={6} md={4}>
                <span className="fa-layers fa-fw my-4">
                  <FontAwesomeIcon icon={faCircle} size="3x" /> 
                  <FontAwesomeIcon icon={faDollarSign} size="1x" className='px-3' color="white" /> 
                </span>
                <h3 className='feature_title'> طرق الدفع </h3>
                <p> طرق الدفع السريعه والموثوقه 100% </p>
              </Col>
            </Row>
          </Container>
      </Container>
      <Container fluid>
        <Col sm={12} className="d-flex justify-content-center my-2">
          <Image src='https://cdn.salla.sa/form-builder/xtMsdUn4O5rteqHH9CFfp9rUGVfaw2IZoz2lKAC8.png' alt='خمس سنوات من العطاء' fluid ></Image>
        </Col>
        <Col sm={12} className="d-flex justify-content-center my-2">
          <Image src='https://cdn.salla.sa/form-builder/jIU5nSbtvT6LQ6LUVTLBQzCtoZZLtkfOhLSujb4Q.png' alt='الدعم الفني عبر واتساب' fluid ></Image>
        </Col>
        <Col sm={12} className="d-flex justify-content-center my-2">
        <Image src='https://cdn.salla.sa/form-builder/nEvrSKN1dHxdDbNKy8tFUzVXjWnbnSDXd5jWCL2x.png' alt='رحلة الاشتراك' fluid ></Image>
        
        </Col>
      </Container>
    </>

  )
}

// export const getServerSideProps: GetServerSideProps = async () => {
//     // return {
//   //   props: { products: res.data.payload },
//   // };
//   // const res = await axios.get(baseUrl+'/seller/product/');
//   // return {
//   //   props: { products: res.data.payload },
//   // };
// };

export default Home
