
import type { NextPage } from 'next'
import Head from 'next/head';
import ProdList from '../components/lists/prodList';
import MainCarousel from '../components/widgets/mainCarousel';
import { Container} from 'react-bootstrap';
import {useSelector,useDispatch  } from "react-redux";
import { selectLayoutState,setMainLayout } from '../store/layoutSlice';
import { useEffect } from 'react';
import { wrapper } from '../store/store';
import { layoutItem } from '../types/layoutItem';
import { fetchMainLayout } from '../utils/requests';

const Home: NextPage = (props:any) => {

  const dispatch=useDispatch()
  const mlayout=useSelector(selectLayoutState)
  useEffect(()=>{
    if(!mlayout.mainLoaded){
      dispatch(setMainLayout(props.main))
    }
  })

  return (
    <>
      <Head>
        <title>Store-App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {mlayout.main.items.map((item:layoutItem,key:any)=>{
        return <Container  key={key} fluid className={item.item_type==='slider' ? 'px-0' : ''} >
          {item.item_type==='slider' ? <MainCarousel></MainCarousel> : <></>  } 
          {(item.item_type==='list') ? <ProdList list={item.attachment.products} ></ProdList> :<></>}
        </Container>
      })}
    </>
  )
}


export const getServerSideProps = wrapper.getServerSideProps(
  () => async () => {

    var data = await fetchMainLayout();
    return {
      props: {main:data.payload},
    };
})




export default Home;

