
import type { NextPage } from 'next'
import Head from 'next/head';
import ProdList from '../components/lists/prodList';
import { Container} from 'react-bootstrap';
import {useSelector  } from "react-redux";
import { selectMainLayoutState } from '../store/layoutSlice';
import { layoutItem } from '../types/layoutItem';
import { getServerSideProps } from '../utils/serverProp';
import LayoutCarousel from '../components/widgets/layoutCarousel';


const Home: NextPage = () => {

  const mlayout=useSelector(selectMainLayoutState)

  return (
    <>
      <Head>
        <title>Store-App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {mlayout.layout.items.map((item:layoutItem,key:any)=>{
        return <Container  key={key} fluid className={item.item_type==='slider' ? 'px-0' : ''} >
          {item.item_type==='slider' ? <LayoutCarousel></LayoutCarousel> : <></>  } 
          {(item.item_type==='list') ? <ProdList list={item.attachment.products} ></ProdList> :<></>}
        </Container>
      })}
    </>
  )
}

export { getServerSideProps };


export default Home;

